### ISSUE TITLE
Enable app sandbox

### ISSUE THREAD

**Issue by nevack** [losnoco/Cog#123]
Tracking issue for App Sandbox problems.
Sandbox support is being done in `sandbox` branch.

**Comment by kode54** [comment]
I think the sandbox issue should implement the Sandbox paths as a preferences or allow list dialog, which lists all the folders the user has allowed. It should allow a user to opt for any folder depth they want, or add a specific folder at will. It should gracefully fail if a user disallows access to a given path. It should be able to check if a requested file or folder is within an already-listed directory, and begin/end access on that directory.

As a helper for begin/end access, the begin access function should return either a handle unique to that path, or a string indicating that path, or the NSURL of the base path, just so it can be saved, and then later passed to the end access function by that caller. Caller should still call begin/end once for each file/folder they need to access, and only end once access is finished.

Also, Sandbox needs to be entitled to full read-write permission for user-requested files, because we need write access to save playlists when the user asks to save one somewhere. Not needed to save the persistent main playlist(s in future) in the Sandbox for recall on startup.

**Comment by kode54** [comment]
This is implemented now.
