### ISSUE TITLE
[FR] If you drag in files 01-07, retain the order on playlist.

### ISSUE THREAD

**Issue by esaruoho** [losnoco/Cog#139]
I'm working on an EP. I have them sorted by filename. so 01 02 03 04 05 06 07.
I drag them to COG.

I expect the result to be 01-07.
The result is: 07, 05, 06, 01, 03, 02, 04.

Any chance this could be fixeded?
<img width="356" alt="Screenshot 2021-04-02 at 23 28 07" src="https://user-images.githubusercontent.com/4966687/113451662-21598c80-940b-11eb-9ca2-a134f1287614.png">

**Comment by kode54** [comment]
This should be fixed by the latest version which I am in the process of building and packaging now, update within the next 20 minutes or so, or possibly later.

The issue was that drops on newer macOS produce "file:///.id=blah" type links, and it was sorting those by their id numbers instead of resolving them to absolute file paths first.

**Comment by kode54** [comment]
Please test this.

**Comment by esaruoho** [comment]
Will check

**Comment by esaruoho** [comment]
ordering fixed! thanks! closing.
