### ISSUE TITLE
Adding FLAC files causes hang

### ISSUE THREAD

**Issue by JanX2** [losnoco/Cog#149]
**Describe**
Adding FLAC files causes hang.

**To Reproduce**
1. Drag FLAC files (or a folder hierarchy containing them) onto the playlist.
2. Cog hangs.
3. Log repeatedly shows entries like this:
2021-05-07 12:34:59.921071+0200 Cog[47253:1966326] -[CoreAudioDecoder close] (line 83) Error closing ExtAudioFile
2021-05-07 12:34:59.921124+0200 Cog[47253:1966326] -[CoreAudioDecoder close] (line 88) Error closing AudioFile

**Expected behavior**
Progress sheet or adding files in the background. Alternatively, very short beach ball.

**Version information:**
 - macOS version: 10.15.7
 - Cog version: Current HEAD: c5ac867

**Additional context**
I have only tried adding files from my server.

**Comment by kode54** [comment]
Clearly the system decoder is broken.

**Comment by kode54** [comment]
Please email me one such FLAC file, and post here what method you are using to access the file. HTTP/S, SMB share, etc.

**Comment by kode54** [comment]
I brought back background loading for all but the first track of an operation, with queued loading for up to 8 tracks at once.

**Comment by JanX2** [comment]
Thanks @kode54. I will test this soon. Do you still require a sample file? I’m accusing the server (Mac OS X 10.12 Server) via SMB. The data is on a disk attached via USB 2.0, but debugging instrumentation shows that bandwidth at least doesn’t appear to be the issue.

**Comment by kode54** [comment]
Prior to the latest update, it would sequentially fetch the properties and metadata for all tracks added to the player. Now it will fetch the first one in the foreground so it can start playing immediately, while it fetches the rest in the background, up to 8 at a time. VGMStream still uses a properties and metadata cache, because its file access API is kind of inefficient, and would end up eating a lot of file handles during the process.

**Comment by kode54** [comment]
Please test again.

**Comment by kode54** [comment]
Closing until OP responds. @JanX2 Please test again.
