### ISSUE TITLE
Removing a song caused the application to freeze and leak memory

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#184]
**Describe**
Removing a song caused the application to freeze and leak memory.

**To Reproduce**
1. Removing a song.
2. Freeze and leak memory.

**Screenshots**

<img width="935" alt="Screen Shot 2021-12-22 at 13 22 31" src="https://user-images.githubusercontent.com/62497891/147102221-c1932499-ff7b-4e02-807c-e5105a480e28.png">

<img width="1104" alt="Screen Shot 2021-12-22 at 13 18 40" src="https://user-images.githubusercontent.com/62497891/147102293-4df18fff-a13f-4fa8-8379-40bb7789800a.png">

<img width="1104" alt="Screen Shot 2021-12-22 at 13 19 47" src="https://user-images.githubusercontent.com/62497891/147102386-c629bb72-dd71-4b07-a44e-6080215a1968.png">

<img width="1104" alt="Screen Shot 2021-12-22 at 13 18 56" src="https://user-images.githubusercontent.com/62497891/147102466-c6f37af0-fb41-40b9-806a-63dce05f6b97.png">

**Version information:**
 - macOS version: 12.1 (21C52)
 - Cog version: 1638 (1638-g7da3324e)

**Comment by kode54** [comment]
I can't reproduce this issue. I have 2413 entries in my playlist, removing them all causes no lock up or leak. Adding another single track and removing it also causes no lock up or leak.

**Comment by Oleg-Chashko** [comment]
This issue happened for the first time in about 2.5 months of use. A very rare bug.

**Comment by Oleg-Chashko** [comment]
I closed the topic, there is no Crash with. Thank you!

**Comment by mrtnpaolo** [comment]
This happens a lot to me, I bring in some hundred songs, play them all. Then I select them all and delete them, add a different set of songs, and when I click play the program hangs for a little bit before figuring out what the stuff to play is.

(Another issue: I use shuffle album mode and often after the first song it plays it stops instead of continuing through the album.)

Yesterday night the worst happened, at some point I received a notification from macOS that I was out of memory and the culprit was cog:

<img width="1440" alt="cog memory leak" src="https://user-images.githubusercontent.com/58419880/149492021-deb41384-540f-43c7-b726-1f5ad2c843c4.png">

Is there something I can do to find some useful log file or information for you to track this down?

**Comment by kode54** [comment]
Literally how many million songs are you adding to your playlist? It does have to load the info for all songs to memory at once, and unloads them when you remove them from the playlist. Sort of. It also has an undo buffer, where it perpetually stores every playlist change you make, including mass add and remove operations. This buffer is cleared on quit.

**Comment by mrtnpaolo** [comment]
Just a couple hundred, something fishy is going on!

**Comment by kode54** [comment]
I would advise updating to the latest version before testing further.

**Comment by mrtnpaolo** [comment]
«Cog 1784 is now available—you have 1611» Good idea! I am gonna try now.
