### ISSUE TITLE
Bug: EQ

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#198]
If you play a list of tracks with different styles of music, the EQ does not always switch the correct EQ setting. 
This problem does not occur when switching tracks manually.

**Version information:**
 - macOS version: 12.2 Beta (21D5039d)
 - Cog version: 1814 (1814-gec8466e5)

**Comment by kode54** [comment]
If the preset list does not contain a near match to the requested genre, then it will pick "Flat".

**Comment by kode54** [comment]
I suggest helping me amend the equalizer presets. They are basically Winamp presets, which are definitely not "80s-95s", but more "95s-99s" in origin. The format is simple. Specific set of bands, range 1-64. 33 is centered, 1 is -12 dB, 64 is +12 dB. Preamp is in the presets, but isn't supported at this time, since none of the presets use it anyway.

There's an extra field I added support for, "altGenres". It should be a JSON array of strings, containing alternate genre names that a given preset should be matched to. Suggestions also welcome, in the form of pull requests against the Winamp.q1.json file in the project root. Or diff logs against the latest version of the file, if you prefer not to be credited.

**Comment by Oleg-Chashko** [comment]
> If the preset list does not contain a near match to the requested genre, then it will pick "Flat".

You don't quite understand me: there is a corresponding preset. But the player automatically plays every next track in the list, the preset does not always select it. But if I start the track myself, the preset is selected correctly.

**Comment by Oleg-Chashko** [comment]
> I suggest helping me amend the equalizer presets. 

- In progress:
![Genre Preset EQ](https://user-images.githubusercontent.com/62497891/150111387-2cf423ce-1241-4d73-b93e-8ae59b0b7b48.png)

**Comment by kode54** [comment]
I noticed. The preset loader wasn't working correctly for running instances without the dialog open, because the notification wasn't being received by the caller. I've changed things to use a different method of applying the presets to the playback equalizer.

**Comment by Oleg-Chashko** [comment]
The playback equalizer presets in version 1830 (1830-g5f82fa57) switch perfectly. 

- But a new bug appeared: the equalizer chart stopped switching.
<img width="705" alt="Screen Shot 2022-01-19 at 14 23 59" src="https://user-images.githubusercontent.com/62497891/150140676-399d1b5a-4518-469f-b600-df56a0744779.png">

**Comment by kode54** [comment]
I've taken a break for now, I'll deal with this in a few days.
