### ISSUE TITLE
ATRAC3 seamless loop not working

### ISSUE THREAD

**Issue by uyjulian** [losnoco/Cog#229]
**Describe**
Seamless loop points in ATRACT3 .at3 files is not respected in single file loop once mode. Instead of jumping to the loop point in the file it just restarts the file from the beginning.

**Version information:***
 - macOS version: 10.14
 - Cog version: 2043

**Comment by kode54** [comment]
Please post your file, and also report to https://github.com/vgmstream/vgmstream

**Comment by uyjulian** [comment]
This is not an issue with vgmstream as doing e.g. `wine /path/to/test.exe -m /path/to/file.at3` correctly identifies the loop points.  

This occurs with ATRAC3 files with loop points. Here is a sample: https://drive.google.com/file/d/1O9-fSPpLVVjajsUVFufIXWxz9xA_sAsi/view?usp=sharing  

This worked correctly in past versions of Cog. I suspect the ffmpeg decoder having priority over the vgmstream decoder causes the loop points to not be read.

**Comment by kode54** [comment]
VGMStream does not handle files with common extensions, intentionally. You need to rename this file to just .at3, or any other conventional .wav file with loop information to .lwav, a fake extension that VGMStream handles.

VGMStream intentionally doesn't take priority, because it decodes literally everything to 16-bit PCM, even floating point or 24-bit files.
