### ISSUE TITLE
Few suggestion and bug reports

### ISSUE THREAD

**Issue by yw4z** [losnoco/Cog#242]
Sorry i dont want to open many posts.

Bug - Miniplayer stays on top even "show mini player on top" not selected
Steps -  i open a mp3 file while cog is not running. cog starts as mini player and stays on top. if i enable then disable "show mini player on top" option, it works as expected then it goes background

Suggestion - Removing border on timestamp results more modern look. also it looks like not vertically centered. sorry i have ocd :)

Suggestion - Placing volume slider as horizontal will be easier to use. here is a example from music app miniplayer mode

![Screen Shot 2022-02-20 at 18 36 42](https://user-images.githubusercontent.com/28517890/154850868-64a6edf2-9b80-402e-894a-89d3b83b4925.jpg)

Suggestion - Adding an option for fixing/linking mini player and full player window width and position can be handy. here is a example i record while ago

![Screen Recording 2019-02-03 at 20 58 30](https://user-images.githubusercontent.com/28517890/154850066-523ace79-67db-4384-8dd1-68ff90bcaed7.gif)

![Screen Recording 2019-02-03 at 20 59 39](https://user-images.githubusercontent.com/28517890/154850071-27891ba9-922b-4ed3-8b8d-2523fc7cddac.gif)

Suggestion - “Quit when playback ends” option could be useful. i mostly play single files in my scenario

Suggestion - Customization option for font size and vertical paddings for playlist section

Suggestion - I was released big sur type icons on my [gumroad page](https://app.gumroad.com/yw4z?sort=newest) for some apps. if you are ok with changing icons i can rework all. also i have a icon replacement pack for cog on there but didnt update for big sur style

Im using big sur and latest cog

This is best audio player in option compared to other ones. thanks for keeping alive this great app. its clean & fast

**Comment by kode54** [comment]
> Bug - Miniplayer stays on top even "show mini player on top" not selected Steps - i open a mp3 file while cog is not running. cog starts as mini player and stays on top. if i enable then disable "show mini player on top" option, it works as expected then it goes background

I'll fix this.


> Suggestion - Removing border on timestamp results more modern look. also it looks like not vertically centered. sorry i have ocd :)

And makes things even weirder for older machines, which don't even obey the sizing style of the app, or obey things like the timestamp field being programmed to resize automatically to fit the text.

Also, I don't control the text positioning, it's centered horizontally in the control, and vertical positioning is controlled by the toolbar control and the text control itself, which just centers the text field with no regard for how it looks.


> Suggestion - Placing volume slider as horizontal will be easier to use. here is a example from music app miniplayer mode

I really don't know what's easier to use about a horizontal slider compared to a vertical one.

> Suggestion - Adding an option for fixing/linking mini player and full player window width and position can be handy. here is a example i record while ago

They're two independent windows, not different styles of the same window.


> Suggestion - “Quit when playback ends” option could be useful. i mostly play single files in my scenario

Considering it. My SO also likes the idea of this feature, for what it's worth.


> Suggestion - Customization option for font size and vertical paddings for playlist section

The playlist font size is already controllable through a Cmd + and Cmd - keys, and the menu actions they actuate. Are you saying you want a font picker that also lets you change which font it uses?


> Suggestion - I was released big sur type icons on my [gumroad page](https://app.gumroad.com/yw4z?sort=newest) for some apps. if you are ok with changing icons i can rework all. also i have a icon replacement pack for cog on there but didnt update for big sur style

I like my current icon set, but if you want to add an alternate icon set that can be enabled at runtime, you can submit a set, and I'll look into adding an option to display them while it's running.


> Im using big sur and latest cog

Nice, which is almost latest macOS. I can't really say the same for all my users, which is why I have to bend over backwards sometimes for compatibility concerns. Like the time display using 13pt text, which looks normal on 10.14 and up, versus using 11pt text, which is required for 10.13 and 10.12.


> This is best audio player in option compared to other ones. thanks for keeping alive this great app. its clean & fast

Cool, thanks.

**Comment by kode54** [comment]
> > Bug - Miniplayer stays on top even "show mini player on top" not selected Steps - i open a mp3 file while cog is not running. cog starts as mini player and stays on top. if i enable then disable "show mini player on top" option, it works as expected then it goes background
> 
> I'll fix this.

Fixed.

> > Suggestion - “Quit when playback ends” option could be useful. i mostly play single files in my scenario
> 
> Considering it. My SO also likes the idea of this feature, for what it's worth.

Implemented now. Setting is in Preferences, under Playlist.
