### ISSUE TITLE
Funky Spectrum Graphics 

### ISSUE THREAD

**Issue by itl20xx** [losnoco/Cog#258]
The spectrum music animation at the top has weird flickering and colors going on. I'm not sure exactly which version this started. I've attached a short recording of it:

https://user-images.githubusercontent.com/101009337/170345239-b6057367-6706-4b89-b4fe-6d000f950ce4.mov

**Comment by kode54** [comment]
Which GPU are you using? The visualizer should only be using Metal graphics on Metal 2 compatible GPUs.

**Comment by itl20xx** [comment]
According to my system info, I'm using Metal GPUFamily macOS 2.

**Comment by itl20xx** [comment]
I wasn't able to get it in a separate window when using that button combo.

**Comment by kode54** [comment]
Since you don't seem to know the model of your GPU, perhaps you can tell us the exact model and SKU of your Mac? I find it strange that Metal Mac family 2 is supported, but it doesn't want to properly support rendering to a transparent window. And the independent window apparently is throwing an exception on creation, since it fails to open at all. (There is also a menu item, under View.)

**Comment by itl20xx** [comment]
Looks like the latest version fixed the graphical bug. Thanks!
