### ISSUE TITLE
Already small fonts are smaller

### ISSUE THREAD

**Issue by reagle** [losnoco/Cog#284]
I received 2405 this morning homebrew and notice the already small fonts are even smaller.

macOS 12.4 21F79 arm64

<img width="1388" alt="Screen Shot 2022-06-23 at 08 58 51" src="https://user-images.githubusercontent.com/596814/175304523-a4bd77c3-5e82-4abd-837f-721e39eb963b.png">

**Comment by reagle** [comment]
The left is a screenshot I took for #283 and the right is the most recent version after I nuked all of the cog install files. I don't see where I'd be able to configure this.

**Comment by kddlb** [comment]
Use cmd-plus/minus to change the playlist’s font size.

**Comment by reagle** [comment]
I realized that command+/- allows me to zoom the font, but upon return the playlist is funky, as per #283.

<img width="1075" alt="Screen Shot 2022-06-23 at 09 02 43" src="https://user-images.githubusercontent.com/596814/175305322-c0b289f2-1797-4f95-a0d7-4d1afad635ad.png">

**Comment by kode54** [comment]
The blank items issue has been fixed. As for font sizes, you must have upgraded from quite a while ago, as I made no changes to the font rendering to the playlist since the first Sandboxed version. In fact, the only font init issue that was changed with the playlist was that it now gets a font with fixed width numerals with a single call, instead of a roundabout way of allocating the sized system font, adding the monospace numerals attribute, then recreating it, again, with the same size. That's clearly a macOS bug, then.
