### ISSUE TITLE
Creeping memory use (especially coreaudio) and occasional hang (redux)

### ISSUE THREAD

**Issue by reagle** [losnoco/Cog#336]
A recurrence of #221: an idle Cog is consuming a surprising amount of memory in itself and coreaudio.

I recently noted this with 2688-g37065adf on MacOS 13.0.1 (22A400) and confirmed with the latest 2722-g5e0a3308.

![SCR-20221207-cgi](https://user-images.githubusercontent.com/596814/206206212-b400fa11-a467-4302-b536-3a3b6ad9f091.png)

**Comment by kode54** [comment]
Cog itself should not be trending upward, and 296.4 MB is about right for a sizable playlist of files with lots of tags. My instance is using 189.0 MB with 1065 files loaded, most of which don't have tags, or don't have more than basic info, because my current playlist is mostly MIDI files.

coreaudiod isn't trending upward here, either. It's sitting at 307.8 MB.

I will listen to a bunch of files and tracks over several hours and let you know if I see them budge from those figures.

**Comment by reagle** [comment]
Those figures were not with things in an egregious state, but I'll start over. I've restarted cog and loaded my typical 40 song folder its 117.5MB . A fresh coreaudiod is 20.8MB.

I'll report back Monday morning. (I don't think my coreaudiod problem is specific to cog, but it seems to prompt it nonetheless.)

**Comment by reagle** [comment]
cog and coreaudiod are behaving as of this morning, but I'll continue to keep an eye on it for the rest of the week.

![SCR-20221212-fyc](https://user-images.githubusercontent.com/596814/207100016-76a3d250-7f37-460e-b269-e3260f25098f.png)

**Comment by reagle** [comment]
Yesterday and this morning's memory. I listened to Cog for about 30 minutes yesterday -- but it's always running.

![SCR-20221214-fi7](https://user-images.githubusercontent.com/596814/207879543-ffede88b-a9ef-444b-82ab-e34b22bc0ad9.png)
...
<img width="436" alt="SCR-20221215-cg1" src="https://user-images.githubusercontent.com/596814/207879653-770ef372-0903-4716-8f1d-fa7231f6932f.png">

I'm going to quit Cog for a day or so and see what happens to coreaudio.

**Comment by reagle** [comment]
My coreaudio seems to be provoked with memory growth independent of cog, so I'm going to close this for now.
