### ISSUE TITLE
Feature request: .gz support

### ISSUE THREAD

**Issue by Brog33** [losnoco/Cog#353]
Mod files are commonly packed with .gz, it would be awesome to have built-in support for it in cog, as it already supports .zip

**Comment by kode54** [comment]
Already supported. If it isn't, something isn't working.

**Comment by Brog33** [comment]
Aha! okay, so i guess it's the naming of the file itself:

Eg. the archive name: "MOD.physical presence.gz" - unpacked is "MOD.physical presence". It needs to be renamed to "physical presence.mod" for the played to recognize it.

**Comment by kode54** [comment]
Ah, yeah, I'll have to look into adding support for Amiga filenames to the player some day. Which will require replacing every single piece of code that calls the Cocoa standard function that returns the extension, with code that can also test the prefix on the filename. Or at least, for the parts that pick file inputs based on extensions, since the file inputs themselves don't usually do their own extension checking, except for maybe VGMStream.

**Comment by Brog33** [comment]
I see. It would certainly be a nice feature to have. I could open an issue for that one instead, if it's not already on there somewhere :)

**Comment by kode54** [comment]
I'll redirect this issue to one I'll open for Amiga filename support.

**Comment by kode54** [comment]
New issue tracking that, feel free to subscribe there:

https://github.com/losnoco/Cog/issues/362
