### ISSUE TITLE
Mini window has strange artifact on 10.13.6

### ISSUE THREAD

**Issue by kode54** [losnoco/Cog#70]
This was sent to me via email by a user. Apparently the latest version's mini window has that artifact on the bottom, but it looks broken in other ways as well.

![Screen Shot 2021-01-07 at 14 48 29](https://user-images.githubusercontent.com/796316/103953035-39648d00-50f6-11eb-9284-73a0772eacff.png)

**Comment by kode54** [comment]
This may be related to your recent changes, @nevack ?

**Comment by nevack** [comment]
I have set window content size height/minHeight/maxHeight to 1 instead of 0, because the other way Cocoa doesn't respect minimum size at all.

Artifact at bottom is separator between content and toolbar.

I can revert this change partially.

> looks broken in other ways as well

I think toolbar was customised by the user, because default layout is below.

![image](https://user-images.githubusercontent.com/8330119/103979245-741a0400-518e-11eb-8fcb-04d475c2cea1.png)

**Comment by kode54** [comment]
No, it's probably just the price to pay for doing a window like this, and probably only looks like that on older systems.

**Comment by nevack** [comment]
> No, it's probably just the price to pay for doing a window like this, and probably only looks like that on older systems.

I can try to enforce minimum size with code and not xib.

**Comment by nevack** [comment]
I think this is fixed. Closing for now
