### ISSUE TITLE
Current time indicator in the toolbar doesn't have a fixed width

### ISSUE THREAD

**Issue by sirburpalot** [losnoco/Cog#78]
The current time indicator in the toolbar should have a fixed width and/or use a monospace font, so as to prevent the other controls from moving around when the time changes.

**Comment by kode54** [comment]
You are correct, but this is a long standing issue. I should probably also modify the formatter for the playing time so it pads to the right based on the current track duration, if known.

**Comment by nevack** [comment]
Nice catch.

**Comment by sirburpalot** [comment]
Unfortunately, switching to using a monospace font didn't entirely fix this: the issue still occurs when the time changes from 9:59 to 10:00, for example.

**Comment by kode54** [comment]
This issue is a little more complex than I thought. As I said, it needs a fix so that it formats the current time to a minimum width of however many digits it takes to display the current track's duration. @nevack if you want to handle this before I boot back into macOS tonight? I can take a look at it later, though.

**Comment by kode54** [comment]
This should be different now, and time field should only change across different tracks with wildly varying lengths.
