### ISSUE TITLE
Drag and drop no longer works on 10.13

### ISSUE THREAD

**Issue by kode54** [losnoco/Cog#90]
Based on this brief email "Drag and drop no longer works after the last Cog’s update (macOS 10.13)."

**Comment by nevack** [comment]
I need more info for this. What is Drag source and Drop destination? I can setup 10.13 VM to reproduce the issue then.

**Comment by kode54** [comment]
I'm sorry, I should have asked them first. It may be the iTunes drag object, since you did completely replace that one with the TV object. I asked them for more information, so I'll wait on that before posting again. (Using the in-app feedback results in personal emails being sent to me, which I then need to post here so they can be worked on by anyone else.)

**Comment by kode54** [comment]
"When I drag files or folders from Finder to Cog nothing happens, i.e. they aren’t added to the playlist. Of course, I can still open them via command-o shortcut, but for some reason this is excruciatingly slow (much slower than in any other app when I open files via command-o)."

**Comment by nevack** [comment]
Thanks. I used app [Pasteboard Viewer (GitHub)](https://github.com/sindresorhus/Pasteboard-Viewer) for debugging Drag&Drop from iTunes / Apple Music.
That's how I found `com.apple.tv.metadata`, it's a common UTI for all apple staff, not only TV. Confusing name, I agree.

On 10.13+ system generates 2 paste objects - one with UTI above and one named `dyn.somegeneratedid` for backward compatibility I think.
UTI is the preferred way to identify pasteboard items.

I'll try to debug Drag&Drop from Finder on 10.13 VM with Pasteboard Viewer. I think the problem is with new [NSPasteboardTypeFileURL(Apple Developer)](https://developer.apple.com/documentation/appkit/nspasteboardtypefileurl?language=objc)

**Comment by kode54** [comment]
Another user has reported the same issue. I'll add a tracking bug for their other request.

**Comment by kode54** [comment]
Another user still has reported that not only is Drag and Drop from Finder broken on 10.13, but also 10.14 and 11.0. I'm sorry I didn't even bother to verify this functionality before releasing it. I'll see what I can do about that pasteboard viewer next time I'm in macOS. Which will be tonight, as I'm also booting into it to update both my systems to the first 11.3 beta.

**Comment by kode54** [comment]
This should be working? Closing.
